Traceback (most recent call last):
  File "/data/gpfs/projects/punim0478/bansaab/linc2/main.py", line 70, in <module>
    vllm_server = ModelServer(
  File "/data/gpfs/projects/punim0478/bansaab/linc2/eval/server.py", line 46, in __init__
    self.engine = LLM(
  File "/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/vllm/utils.py", line 1096, in inner
    return fn(*args, **kwargs)
  File "/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 243, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
  File "/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 514, in from_engine_args
    vllm_config = engine_args.create_engine_config(usage_context)
  File "/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 1137, in create_engine_config
    model_config = self.create_model_config()
  File "/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 1026, in create_model_config
    return ModelConfig(
  File "/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/vllm/config.py", line 343, in __init__
    hf_config = get_config(self.hf_config_path or self.model,
  File "/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/vllm/transformers_utils/config.py", line 330, in get_config
    config = load_params_config(model, revision, token=HF_TOKEN, **kwargs)
  File "/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/vllm/transformers_utils/config.py", line 636, in load_params_config
    assert isinstance(config_dict, dict)
AssertionError

real	3m0.886s
user	0m6.665s
sys	0m1.108s
